MODEL:
  META_ARCHITECTURE: Baseline
  DEVICE: cpu

  BACKBONE:
    NAME: build_resnet_backbone
    NORM: BN
    DEPTH: 18x
    LAST_STRIDE: 1
    FEAT_DIM: 512
    WITH_IBN: True
    PRETRAIN: True
    PRETRAIN_PATH: C:\Users\cyka\.cache\torch\hub\checkpoints\resnet18-f37072fd.pth

  HEADS:
    NAME: EmbeddingHead
    POOL_LAYER: GlobalAvgPool
    WITH_BNNECK: True
    CLS_LAYER: Linear

  LOSSES:
    NAME: ("CrossEntropyLoss", "Cosface",)

    CE:
      EPSILON: 0.12
      SCALE: 1.

    TRI:
      MARGIN: 0.3
      SCALE: 1.0
      HARD_MINING: False

DATASETS:
  NAMES: ("BikePerson",)
  TESTS: ("BikePerson",)

INPUT:
  SIZE_TRAIN: [384, 128]
  SIZE_TEST: [384, 128]

  FLIP:
    ENABLED: True

DATALOADER:
  SAMPLER_TRAIN: TrainingSampler
  NUM_INSTANCE: 1
  NUM_WORKERS: 1

SOLVER:
  AMP:
    ENABLED: False
  OPT: Adam
  MAX_EPOCH: 60
  BASE_LR: 0.0007
  BIAS_LR_FACTOR: 1.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  SCHED: CosineAnnealingLR
  DELAY_EPOCHS: 20
  ETA_MIN_LR: 0.0000007

  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 500

  CHECKPOINT_PERIOD: 1

TEST:
  EVAL_PERIOD: 1
  IMS_PER_BATCH: 64

CUDNN_BENCHMARK: False

OUTPUT_DIR: ../logs/bicycle_person_reid
